trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'fabiovg10/react-pdn'

steps:

- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile.prod

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      v2

- task: CopyFiles@2
  displayName: 'Copy Files to:$(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: infraestructura
    Contents: '**.tf'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'