trigger:
- master

variables:
  imageName: 'fabiovg10/react-pdn'
  vmImageName: 'ubuntu-latest'
  tag: 'BuildId_$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Dockerfile stage
  jobs:
  - job: BuildDockerFileJob
    displayName: Build Dockerfile Job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Dockerfile.prod
        containerRegistry: DockerHubLogin
        tags: |
          $(tag)

- stage: PublishTFArtifacts
  displayName: Publish tf artifacts
  jobs:
  - job: PublishTFArtifactsJob
    displayName: Publish tf artifacts Job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to:$(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: infraestructura
        Contents: '**.tf'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
