trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'fabiovg10/react-pdn'

stages:
- stage: BuildDockerFile
  steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: Dockerfile.prod
        tags: latest
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: DockerHubLogin  
        repository: $(imageName)
        command: push
        tags: latest

- stage: Deploy
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to:$(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: infraestructura
      Contents: '**.tf'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
