trigger:
- master

variables:
  imageName: 'fabiovg10/react-pdn'
  vmImageName: 'ubuntu-latest'
  tag: 'BuildId_$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Dockerfile stage
  jobs:
  - job: BuildDockerFileJob
    displayName: Build Dockerfile Job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: Dockerfile.prod
        containerRegistry: DockerHubLogin
        tags: |
          latest

- stage: PublishTFArtifacts
  displayName: Publish tf artifacts
  jobs:
  - job: PublishTFArtifactsJob
    displayName: Publish tf artifacts Job
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files to:$(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: infraestructura
        Contents: '**.tf'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
- stage: Deploy
  displayName: Deploy to container
  jobs:
  - job: DeployJob
    displayName: Deploy to container job
    pool: 
      vmImage: vs2017-win2016
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
      displayName: 'Terraform init'
      inputs:
        TemplatePath: '$(Build.ArtifactStagingDirectory)'
        Arguments: init
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameARM: 'Evaluación gratuita (624b94b8-99b4-4a2d-b386-84385e044d72)'
    - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
      displayName: 'Terraform plan'
      inputs:
        TemplatePath: '$(Build.ArtifactStagingDirectory)'
        Arguments: plan
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameARM: 'Evaluación gratuita (624b94b8-99b4-4a2d-b386-84385e044d72)'
    - task: petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform.Xpirit-Vsts-Release-Terraform.Terraform@2
      displayName: 'Terraform apply'
      inputs:
        TemplatePath: '$(Build.ArtifactStagingDirectory)'
        Arguments: 'apply -auto-approve'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameARM: 'Evaluación gratuita (624b94b8-99b4-4a2d-b386-84385e044d72)'


